name: nlp
channels:
  - defaults
  - conda-forge
  - pytorch
  - huggingface
  - nvidia
dependencies:
  - python=3.10
  - ipykernel
  - numpy
  - pandas
  - networkx
  - pytorch
  - pytorch-cuda=11.7 
  - torchvision
  - torchaudio
  - transformers
  - pip
  - pip:
    - scikit-learn
    - tqdm
    - evaluate